
# Inference opts
seed: 128  # 随机数种子
device: 'cuda:0'  # GPU设备
img_read_method: 'rgb'  # 使用哪种方式读取图像，支持 gray、rgb、unchanged
use_frame_align: False  # 是否使用帧对齐
use_second_classify: False  # 是否使用二级分类器
second_classify_method: 'filter_conf'  # 二级分类器方法，支持 filter_conf（使用一二级conf相乘）、filter_pos（直接使用二级分类器判断正负样本）
conf_threshold: 0.1  # 一级检测器和二级分类器置信度相乘的阈值
align_predictor_yaml: ./air_track/aligner/config/predict.yaml  # 帧对齐预测配置文件
detect_predictor_yaml: ./air_track/detector/config/predict_dalachi.yaml  # 检测器预测配置文件
classify_predictor_yaml: ./air_track/classifier/config/predict.yaml  # 分类器预测配置文件

# 数据集路径及文件类型 
dataset_params:
  data_dir: '/media/linana/1276341C76340351/yanqing_orig_data/0912_JD_part'
  img_folder: 'rgb'  # 完整路径为data_dir/part/Images
  label_folder: 'label'  # 完整路径为data_dir/part/labels
  label_file: 'ImageSets/groundtruth.csv'  # 完整路径为data_dir/part/ImageSets
  # 图像和标签类型
  img_format: '.jpg'
  gt_format: '.txt'

  stage_train: 'train'
  stage_valid: 'val'
  stage_test: 'test'
  classes: [
    'himars_laucher',
    'hismars_carrier',
    'jinbei',
    'jinbei-fake',
    'haimars_laucher-fake',
    'car',
    'LT-2000',
    'tianbing-fasheche',
    'aiguozhe-fasheche',
    'tiangong-fasheche',
    'tianbing-leidache',
    'aiguozhe-leidache',
    'tiangong-leidache',
    'tianbing-zhihuiche',
    'aiguozhe-zhihuiche',
    'tiangong-zhihuiche',
    'hanma',
    'szb',
    'himars_laucher-wzw'
  ]
  # 目标类别数
  nb_classes: 19

  # 测试集划分
  part_val: ['14']
  part_test: ['14']
  img_size: [640, 360]  # 输入图像尺寸(w, h)
  max_pixel: 255  # 图像最大像素数
