
# Inference opts
seed: 128  # 随机数种子
device: 'cuda:0'  # GPU设备
img_read_method: 'gray'  # 使用哪种方式读取图像，支持 gray、rgb、unchanged
use_frame_align: False  # 是否使用帧对齐
use_second_classify: False  # 是否使用二级分类器
second_classify_method: 'filter_pos'  # 二级分类器方法，支持 filter_conf（使用一二级conf相乘）、filter_pos（直接使用二级分类器判断正负样本）
conf_threshold: 0.1  # 一级检测器和二级分类器置信度相乘的阈值
align_predictor_yaml: ./air_track/aligner/config/predict.yaml  # 帧对齐预测配置文件
detect_predictor_yaml: ./air_track/detector/config/predict_zbzx.yaml  # 检测器预测配置文件
classify_predictor_yaml: ./air_track/classifier/config/predict.yaml  # 分类器预测配置文件
# 可选传入各个模块模型路径
#align_model_path: ''  # 帧对齐模型路径
detect_model_path: '/home/csz_xishu2/PycharmProjects/github/zhuang5252/AirTrack/model_saved/detect_model/official_resnet/OfficialResNet/ResNet18/zbzx_coarse_visible_20260317/zbzx_coarse_visible_20260317.onnx'  # 检测器模型路径
#classify_model_path: ''  # 分类器模型路径

# 数据集路径及文件类型
dataset_params:
  data_dir: '/home/csz_xishu2/data/zbzx_data/version_2/coarse_visible_val_data'
  img_folder: 'images'  # 完整路径为data_dir/part/Images
  label_folder: 'labels'  # 完整路径为data_dir/part/ImageSets
  label_file: 'ImageSets/groundtruth.csv'  # 完整路径为data_dir/part/ImageSets
  # 图像和标签类型
  img_format: '.png'
  gt_format: '.txt'

  stage_train: 'train'
  stage_valid: 'val'
  stage_test: 'test'
  classes: [
    'point',
    'quadrotor',
    'quadrotor6',
    'fixedwing',
    'other'
  ]
  # 目标类别数
  nb_classes: 5

  # 测试集划分
  part_train: []
  part_val: []
#  part_test: ['1_3_1', '1_4', '2_1', '2_2']
#  part_test: ['2_1', '2_2']
#  part_test: ['1_2']
#  part_test: ['20260305_jy_ftv_640_merge', '20260305_jy_ftv_background_merge', '20260112_jy_itv_640_merge',
#              '20260112_jy_itv_background_merge', '20260305_jy_itv_640_merge', '20260112_jy_ctv_640_merge',
#              '20260305_jy_itv_background_merge', '20260305_jy_ctv_background_merge',
#              '20260305_jy_ctv_640_merge', '20260112_jy_ftv_640_merge']
  part_test: ['20260305_jy_itv_1024_merge', '20260112_jy_itv_1024_merge', '20260305_jy_ftv_background_merge',
              '20260112_jy_ctv_1024_merge', '20260112_jy_ftv_1024_merge', '20260112_jy_itv_background_merge',
              '20260305_jy_ftv_1024_merge', '20260305_jy_itv_background_merge',
              '20260305_jy_ctv_background_merge', '20260305_jy_ctv_1024_merge']
  img_size: [1024, 1024]  # 输入图像尺寸(w, h)
  max_pixel: 255  # 图像最大像素数
