# predict opts
model_path: '/home/csz_changsha/PycharmProjects/github/zhuang5252/AirTrack_all/AirTrack_multi_frame/model_saved/TrEstimatorTsm/Aligner_angle_weight_20/minimum_loss.pt'
test_data_dir: '/home/csz_changsha/data/test_data/single_channel_人工选择'
seed: 128  # 固定随机数种子
device: 'cuda:0'
visualize_flag: True  # 是否可视化帧对齐结果
visualize_save_dir: '/home/csz_changsha/data/test_data/single_channel_20250409_1011_2'  # 可视化结果保存路径

# 数据集路径及文件类型
img_folder: 'Images'  # 完整路径为data_dir/part/Images
label_file: 'ImageSets/groundtruth.csv'  # 完整路径为data_dir/part/ImageSets

# 图像和标签类型
img_format: '.jpg'
#img_format: '.png'
gt_format: '.csv'

# 构建标签的均匀分布的像素位置
points_shape: (2, 16, 20)  # 需要与模型的输出相匹配

# opts
max_pixel: 255  # 图像最大像素值

# model opts
model_params:
  model_type: 'align_model'
  model_cls: 'TrEstimatorTsm'
  base_model_name: 'resnet34'
  input_channel: 1  # 模型输入通道数，需要与下方dataset_params中的use_gray保持一致
  duration: 2  # 时间步数
  weight_scale: 3  # 权重系数
  pretrained: False  # 是否使用预训练模型

# dataset opts
dataset_params:
  img_read_method: 'gray'  # 使用哪种方式读取图像，支持 gray、rgb、unchanged，需要与上方model_params中的input_channel保持一致
  img_size: [640, 512]  # w, h
  downscale: 1  # 原始图像缩放比例
  sigma_scale: 0.0025  # 图像缩放参数
  sigma_angle: 0.2  # 图像旋转参数
  sigma_offset: 6.0  # 图像位移参数
