
# 三种模式
stage_train: 'train'
stage_valid: 'val'
stage_test: 'test'

# 数据集路径及文件类型
data_dir: '/home/csz_changsha/data/0314/0314shuju'
img_folder: 'ir'  # 完整路径为data_dir/stage/Images
label_folder: 'ir_label'  # 完整路径为data_dir/stage/labels

# 图像和标签类型
img_format: '.jpg'
gt_format: '.txt'

# 数据集的划分
part_train: ['DJI_20200101000602_0001_S_frames_1920x1080', 'DJI_20200101001132_0002_S_frames_1920x1080',
    'DJI_20200101001907_0003_S_frames_1920x1080', 'DJI_20200101002803_0004_S_frames_1920x1080',
    'DJI_20200101003919_0006_S_frames_1920x1080', 'DJI_20200101004420_0007_S_frames_1920x1080',
    'DJI_20200101005939_0010_S_frames_1920x1080']
part_val: ['DJI_20200101004928_0008_S_frames_1920x1080']
part_test: ['DJI_20200101005509_0009_S_frames_1920x1080']

# 目标类别
classes: [
    'Himars_launcher',
    'Himars_launcher_fake',
    'Hummer',
]
# 目标类别数
nb_classes: 3

# 帧对齐保存的pkl文件
transforms_dir: ''

# dataset中的frames格式
# 只做展示使用
frame: {
    'part',
    'flight_id',
    'frame_num',
    'img_name',
    'img_path',
    'have_distance',
    'img_width',
    'img_height',
    'detections',
}
# 只做展示使用
detection: {
        'target_id',
        'cls_name',
        'distance',
        'is_above_horizon',
        'cx',
        'cy',
        'w',
        'h',
    }

# opts
max_pixel: 255  # 图像像素最大值
offset_scale: 256.0
