
# 三种模式
stage_train: 'train'
stage_valid: 'val'
stage_test: 'test'

# 数据集路径及文件类型
data_dir: '/home/csz_changsha/data/yanqing_data/0611_processed'
img_folder: 'images'  # 完整路径为data_dir/stage/Images
label_folder: 'labels'  # 完整路径为data_dir/stage/labels

# 图像和标签类型
img_format: '.jpg'
gt_format: '.txt'

# 支持直接指定part_train、part_val、part_test 优先级高于 parts_config_path
# 数据集的划分（支持直接指定part_train、part_val、part_test或者直接指定数据划分配置文件 parts_config_path）
#part_train: ['dataset']
#part_val: ['dataset']
#part_test: ['dataset']

# 数据集parts配置文件，支持json和csv两种，参见template_dataset.csv、template_dataset.json
parts_config_path: '/media/linana/1276341C76340351/csz/github/AirTrack/air_track/detector/config/template_dataset.csv'

# 目标类别
classes: [
  '1',
  '2',
  '3',
  '4'
]
# 目标类别数
nb_classes: 4

# dataset中的frames格式
# 只做展示使用
frame: {
    'part',
    'flight_id',
    'frame_num',
    'img_name',
    'img_path',
    'have_distance',
    'detections',
    'error'
}
# 只做展示使用
detection: {
        'cls_name',
        'target_id',
        'distance',
        'is_above_horizon',
        'cx',
        'cy',
        'w',
        'h',
    }

# opts
max_pixel: 255  # 图像像素最大值
offset_scale: 256.0
